apiVersion: v1
kind: Secret
metadata:
  name: cityasist-secrets
type: Opaque
data:
  jwtSecret: {{ .Values.env.JWT_SECRET | b64enc }}
  adminPassword: {{ .Values.env.APP_ADMIN_PASSWORD | b64enc }}
