apiVersion: v1
kind: Service
metadata:
  name: cityasist
spec:
  type: {{ .Values.service.type }}
  selector:
    app: cityasist
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
